(define (problem dronesprob)

(:domain Drones)

(:objects 
	Drone_1 Drone_2 Drone_3 – drone
	mobilePhone lipgloss toy hairBrush wallet – package
	Headquarters – base
	;E162RJ SW85TG W30PL E105GJ SW197WP – destination
	Spring65 Thorpe97 Grimsby108 Grove91 Swansea77 HQ-Location - location)

(:init
	(at Drone_1 HQ-Location)
	(at Drone_2 HQ-Location)
	(at Drone_3 HQ-Location)
	(at mobilePhone HQ-Location)
	(at lipgloss HQ-Location)
	(at toy HQ-Location)
	(at hairBrush HQ-Location)
	(at wallet HQ-Location)
	(at Headquarters HQ-Location)
	;(at E162RJ Spring65)
	;(at SW85TG Thorpe97)
	;(at W30PL Grimsby108)
	;(at E105GJ Grove91)
	;(at SW197WP Swansea77)
	(empty Drone_1)
	(empty Drone_2)
	(empty Drone_3)
	(available Drone_1)
	(available Drone_2)
	(available Drone_3)
	(= (time-to-arrive HQ-Location Spring65 Drone_1) 10)
	(= (time-to-arrive Spring65 HQ-Location Drone_1) 10)
	(= (time-to-arrive HQ-Location Thorpe97 Drone_1) 15)
	(= (time-to-arrive Thorpe97 HQ-Location Drone_1) 15)
	(= (time-to-arrive HQ-Location Grimsby108 Drone_1) 7)
	(= (time-to-arrive Grimsby108 HQ-Location Drone_1) 7)
	(= (time-to-arrive HQ-Location Grove91 Drone_1) 17)
	(= (time-to-arrive Grove91 HQ-Location Drone_1) 17)
	(= (time-to-arrive HQ-Location Swansea77 Drone_1) 20)
	(= (time-to-arrive Swansea77 HQ-Location Drone_1) 20)
	(= (drone-charge Drone_1) 100)
	(= (drone-charge Drone_2) 80)
	(= (drone-charge Drone_3) 90)
	(= (charge-required HQ-Location Spring65) 20)
	(= (charge-required Spring65 HQ-Location) 20)
	(= (charge-required HQ-Location Thorpe97) 30)
	(= (charge-required Thorpe97 HQ-Location) 30)
	(= (charge-required HQ-Location Grimsby108) 25)
	(= (charge-required Grimsby108 HQ-Location) 25)
	(= (charge-required HQ-Location Grove91) 45)
	(= (charge-required Grove91 HQ-Location) 45)
	(= (charge-required HQ-Location Swansea77) 10)
	(= (charge-required Swansea77 HQ-Location) 10)
	(= (recharge-time Drone_1) 10)
	(= (recharge-time Drone_3) 10))
(:goal (and
	;(delivered mobilePhone)
	(at mobilePhone Spring65)
	(at lipgloss Thorpe97)
	(at toy Grimsby108)
	(at hairBrush Grove91)
	(at wallet Swansea77)
	(at Drone_1 HQ-Location)
	(at Drone_2 HQ-Location)
	(at Drone_3 HQ-Location))))