(define (problem dronesprob)

(:domain Drones)

(:objects 
	Drone_1 Drone_2 Drone_3 Drone_4 Drone_5 Drone_6 – drone
	mobilePhone lipgloss toy hairBrush wallet console pc – package
	Headquarters – base
	E162RJ SW85TG W30PL E105GJ SW197WP N21PK – destination
	65Spring 97Thorpe 108Grimsby 91Grove 77Swansea 12BOlsen – location)

(:init
	(at Drone_1 HQ-Location)
	(at Drone_2 HQ-Location)
	(at Drone_3 HQ-Location)
	(at Drone_4 HQ-Location)
	(at Drone_5 HQ-Location)
	(at Drone_6 HQ-Location)

	(at mobilePhone HQ-Location)
	(at lipgloss HQ-Location)
	(at toy HQ-Location)
	(at hairBrush HQ-Location)
	(at wallet HQ-Location)
	(at console HQ-Location)
	(at pc HQ-Location)
	(at Headquarters HQ-Location)
	(at E162RJ 65Spring)
	(at SW85TG 97Thorpe)
	(at W30PL 108Grimsby)
	(at E105GJ 91Grove)
	(at SW197WP 77Swansea)
	(at N21PK 12BOlsen)
	(empty Drone_1)
	(empty Drone_2)
	(empty Drone_3)
	(empty Drone_4)
	(empty Drone_5)
	(empty Drone_6)
	(available Drone_1)
	(available Drone_2)
	(available Drone_3)
	(available Drone_4)
	(available Drone_5)
	(available Drone_6)
	(= (time-to-arrive HQ-Location 65Spring Drone_1) 10)
	(= (time-to-arrive 65Spring HQ-Location Drone_1) 10)
	(= (time-to-arrive HQ-Location 97Thorpe Drone_3) 15)
	(= (time-to-arrive 97Thorpe HQ-Location Drone_3) 15)
	(= (time-to-arrive HQ-Location 108Grimsby Drone_2) 7)
	(= (time-to-arrive 108Grimsby HQ-Location Drone_2) 7)
	(= (time-to-arrive HQ-Location 91Grove Drone_1) 17)
	(= (time-to-arrive 91Grove HQ-Location Drone_1) 17)
	(= (time-to-arrive HQ-Location 77Swansea Drone_4) 20)
	(= (time-to-arrive 77Swansea HQ-Location Drone_4) 20)
	(= (time-to-arrive HQ-Location 12BOlsen Drone_5) 5)
	(= (time-to-arrive 12BOlsen HQ-Location Drone_5) 5)
	(= (time-to-arrive HQ-Location 77Swansea Drone_6) 20)
	(= (time-to-arrive 77Swansea HQ-Location Drone_6) 20)
	(= (drone-charge Drone_1) 100)
	(= (drone-charge Drone_2) 80)
	(= (drone-charge Drone_3) 90)
	(= (drone-charge Drone_4) 100)
	(= (drone-charge Drone_5) 90)
	(= (drone-charge Drone_6) 95)
	(= (charge-required HQ-Location 65Spring) 20)
	(= (charge-required 65Spring HQ-Location) 20)
	(= (charge-required HQ-Location 97Thorpe) 30)
	(= (charge-required 97Thorpe HQ-Location) 30)
	(= (charge-required HQ-Location 108Grimsby) 25)
	(= (charge-required 108Grimsby HQ-Location) 25)
	(= (charge-required HQ-Location 91Grove) 45)
	(= (charge-required 91Grove HQ-Location) 45)
	(= (charge-required HQ-Location 77Swansea) 10)
	(= (charge-required 77Swansea HQ-Location) 10)
	(= (charge-required HQ-Location 12BOlsen) 5)
	(= (charge-required 12BOlsen HQ-Location) 5)
	(= (recharge-time Drone_1) 10)
	(= (recharge-time Drone_3) 10))
(:goal (and
	(at Drone_1 HQ-Location)
	(at Drone_2 HQ-Location)
	(at Drone_3 HQ-Location)
	(at Drone_4 HQ-Location)
	(at Drone_5 HQ-Location)
	(at Drone_6 HQ-Location)
	(at mobilePhone 65Spring)
	(at lipgloss 97Thorpe)
	(at toy 108Grimsby)
	(at hairBrush 91Grove)
	(at wallet 77Swansea)
	(at console 12BOlsen)
	(at pc 97Thorpe)))
